# Generated by Django 3.1.6 on 2021-05-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tag',
            new_name='department_name',
        ),
    ]
