# Generated by Django 3.1.6 on 2021-05-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20210525_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department_name',
            new_name='department',
        ),
    ]
